security:
    providers:
        in_memory:
            memory:
                users:
                    documentation:
                        password: '%env(USER_DOCUMENTATION_PASSWORD)%'
                        roles: 'ROLE_DOCUMENTATION'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: '^/api/docs', roles: 'ROLE_DOCUMENTATION' }
