version: '2'

services:
    db:
        image: timescale/timescaledb
        ports:
          - 5432:5432
        volumes:
            - "./.data/db:/var/lib/postgresql/"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        container_name: db
        networks:
          - bicing-local-network
    php:
        build: .
        volumes:
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        networks:
          - bicing-local-network
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./logs/nginx/:/var/logs/nginx
        networks:
          - bicing-local-network
networks:
   bicing-local-network:
    external: true
