version: '2'

services:
    db:
        image: timescale/timescaledb
        ports:
          - 5432:5432
        volumes:
            - "./.data/db:/var/lib/postgresql/"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        container_name: db
        networks:
          - bicing-local-network
    php:
        build:
            context: docker/php7-fpm
        volumes:
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        networks:
          - bicing-local-network

networks:
   bicing-local-network:
    external: true
