parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Domain}'

    App\Infrastructure\BicingApi\HttpAvailabilityStationQuery:
        arguments: ['@eight_points_guzzle.client.bicing_api', '@jms_serializer' ]

    app.use_case.create_station_handler:
        class: App\Application\UseCase\Handler\CreateStationHandler
        arguments: ['@App\Domain\Model\Station\StationRepositoryInterface']
        public: true
        tags:
            - { name: command_handler, handles: App\Application\UseCase\Command\CreateStationCommand}
    app.use_case.assign_station_state_to_station_handler:
        class: App\Application\UseCase\Handler\AssignStationStateToStationHandler
        arguments: ['@App\Domain\Model\Station\StationRepositoryInterface', '@App\Domain\Model\Station\StationStateRepositoryInterface']
        public: true
        tags:
            - { name: command_handler, handles: App\Application\UseCase\Command\AssignStationStateToStationCommand }

    app.use_case.refresh_last_station_state_by_station_cache_handler:
      class: App\Application\UseCase\Handler\RefreshLastStationStateByStationCacheHandler
      arguments:
      - '@App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQueryCache.inner'
      - '@App\Infrastructure\Persistence\Doctrine\Cache\DoctrineLastStationStateByStationCache'
      public: true
      tags:
        - { name: command_handler, handles: App\Application\UseCase\Command\RefreshLastStationStateByStationCacheCommand }

    SimpleBus\Message\Bus\MessageBus: '@command_bus'

    App\Domain\Model\Station\StationRepositoryInterface:
        class: 'App\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationRepository'

    App\Domain\Model\Station\StationStateRepositoryInterface:
        class: 'App\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationStateRepository'

    app.infrastructure.doctrine.last_station_state_by_station.cache:
      class: 'Doctrine\Common\Cache\FilesystemCache'
      arguments: ['%kernel.cache_dir%']

    App\Infrastructure\Persistence\Doctrine\Cache\DoctrineLastStationStateByStationCache:
      arguments: ['@app.infrastructure.doctrine.last_station_state_by_station.cache']

    App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQuery: ~
    App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQueryCache:
      decorates: 'App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQuery'
      arguments:
      - '@App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQueryCache.inner'
      - '@App\Infrastructure\Persistence\Doctrine\Cache\DoctrineLastStationStateByStationCache'

    App\Application\UseCase\DataProvider\LastStationStateByStationDataProvider:
      arguments: ['@App\Infrastructure\Persistence\Doctrine\Query\DoctrineLastStationStateByStationQueryCache']
      tags: [ { name: 'api_platform.collection_data_provider'} ]
