parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Domain}'

    App\Infrastructure\BicingApi\HttpAvailabilityStationQuery:
        arguments: ['@guzzle.client.bicing_api', '@jms_serializer' ]

    app.use_case.create_station_handler:
        class: App\Application\UseCase\Handler\CreateStationHandler
        arguments: ['@App\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationRepository']
        public: true
        tags:
            - { name: command_handler, handles: App\Application\UseCase\Command\CreateStationCommand}
    app.use_case.assign_station_state_to_station_handler:
        class: App\Application\UseCase\Handler\AssignStationStateToStationHandler
        arguments: ['@App\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationRepository', '@App\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationStateRepository']
        public: true
        tags:
            - { name: command_handler, handles: App\Application\UseCase\Command\AssignStationStateToStationCommand }
